#!/usr/bin/env bash
# bh-delivery kit resolver. Generated by install-shims.sh — do not edit.
#
#   scripts/kit-root.sh                      prints the resolved kit root
#   scripts/kit-root.sh scripts/pr-open.sh …  execs that kit script with the rest of the args
#
# Resolution: $BH_DELIVERY_ROOT if set, else the installPath of bh-delivery@bh-delivery in
# ~/.claude/plugins/installed_plugins.json.
#
# Then one of two checks, chosen by the profile's kit_version:
#   <exact version>  the kit's plugin.json version must equal it; any mismatch exits 3.
#                    Never falls back to another version.
#   latest           track whatever is installed — no version compare. Instead the SHIM SET
#                    is asserted: every operational kit script must have a shim here, so a
#                    kit that added one fails fast with the fix instead of dying mid-run.
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
profile="${BH_DELIVERY_PROFILE:-$repo_root/.claude/delivery-profile.yaml}"

fixit() {
  echo "   Fix: claude plugin marketplace add Blaze212/bh-delivery && claude plugin install bh-delivery@bh-delivery" >&2
  echo "   (or export BH_DELIVERY_ROOT=/path/to/bh-delivery to point at a local checkout)" >&2
  exit 3
}

# kit_version is a flat scalar on purpose so this grep works with no YAML parser.
#
# The trailing `|| true` is load-bearing. Under `set -euo pipefail`, a profile that EXISTS
# but carries no kit_version line makes grep exit 1, the pipeline inherits it, and `set -e`
# kills the script on this very line — before the missing-pin diagnostic below can run. The
# whole contract of this resolver is that a bad or absent pin fails LOUDLY with exit 3 and
# the fix-it command; a bare `exit 1` and no message is the one outcome it must never have.
want=""
if [ -f "$profile" ]; then
  want="$(grep -E "^kit_version:" "$profile" | head -1     | sed -E "s/^kit_version:[[:space:]]*//; s/[\"']//g; s/[[:space:]]*(#.*)?$//" || true)"
fi
if [ -z "$want" ]; then
  echo "bh-delivery: no kit_version in $profile — cannot verify the kit pin." >&2
  fixit
fi

root="${BH_DELIVERY_ROOT:-}"
if [ -z "$root" ]; then
  installed="$HOME/.claude/plugins/installed_plugins.json"
  if [ ! -f "$installed" ]; then
    echo "bh-delivery: $installed not found — the kit plugin is not installed." >&2
    fixit
  fi
  root="$(node -e '
    const fs = require("fs");
    let j;
    try { j = JSON.parse(fs.readFileSync(process.argv[1], "utf8")); } catch { process.exit(0); }
    // Three shapes have shipped: a flat { "name@marketplace": {installPath} } map, a
    // { plugins: { "name@marketplace": … } } map, and a nested
    // { marketplaces: { <mkt>: { plugins: { <name>: … } } } }. In the second, the value is
    // an ARRAY of install records (one per scope), which is what this machine writes — so
    // flatten arrays rather than assuming an object. Guessing wrong here looks like
    // "not installed", which sends the reader off fixing an install that is already fine.
    const cands = [];
    cands.push(j["bh-delivery@bh-delivery"]);
    if (j.plugins) cands.push(j.plugins["bh-delivery@bh-delivery"], j.plugins["bh-delivery"]);
    const nested = j.marketplaces && j.marketplaces["bh-delivery"];
    if (nested && nested.plugins) cands.push(nested.plugins["bh-delivery"]);
    for (const c of cands.flatMap((c) => (Array.isArray(c) ? c : [c]))) {
      if (c && c.installPath) { process.stdout.write(c.installPath); break; }
    }
  ' "$installed" 2>/dev/null || true)"
  if [ -z "$root" ]; then
    echo "bh-delivery: no installPath for bh-delivery@bh-delivery in $installed." >&2
    fixit
  fi
fi

manifest="$root/.claude-plugin/plugin.json"
if [ ! -f "$manifest" ]; then
  echo "bh-delivery: resolved kit root '$root' has no .claude-plugin/plugin.json." >&2
  fixit
fi
have="$(node -e 'process.stdout.write(String(JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")).version||""))' "$manifest")"

# `kit_version: latest` tracks whatever kit is installed, so there is no version to
# compare. What replaces the check is not nothing — it is the assertion that actually
# breaks a tracking repo: a kit release that ADDS an operational script leaves this repo
# with no shim for it, and the first symptom is a compiled step dying on
# "scripts/<new>.sh: No such file or directory" mid-run. So on `latest` we verify the SHIM
# SET on every call and fail loudly, with the one command that fixes it, BEFORE any work
# starts. A pinned repo keeps the exact-version check and is unaffected.
if [ "$want" = "latest" ] || [ "$want" = "LATEST" ]; then
  missing=""
  for kitscript in "$root"/scripts/*.sh; do
    [ -f "$kitscript" ] || continue
    name="$(basename "$kitscript")"
    # No `case` here on purpose: this whole resolver is a heredoc inside $( … ), and a
    # case pattern's unbalanced `)` closes that command substitution early — the file
    # still looks right and stops parsing at this line.
    if [ "${name#_}" != "$name" ] || [ "$name" = "install-shims.sh" ]; then
      continue                          # kit-internal / human-run: never shimmed
    fi
    [ -f "$repo_root/scripts/$name" ] || missing="$missing $name"
  done
  if [ -n "$missing" ]; then
    echo "bh-delivery: kit $have ships script(s) this repo has no shim for:$missing" >&2
    echo "   kit_version is 'latest', so the kit moved under this repo and the shims are stale." >&2
    echo "   Fix: \"\$(claude plugin path bh-delivery)/scripts/install-shims.sh\"" >&2
    exit 3
  fi
elif [ "$have" != "$want" ]; then
  echo "bh-delivery: kit version mismatch — this repo pins kit_version $want, the installed kit is $have." >&2
  echo "   Either update the pin in $profile (a green one-line PR), install the pinned kit," >&2
  echo "   or set kit_version: latest to track whatever is installed." >&2
  fixit
fi

if [ "$#" -eq 0 ]; then
  printf '%s\n' "$root"
  exit 0
fi

target="$1"; shift
if [ ! -x "$root/$target" ]; then
  echo "bh-delivery: kit $root has no executable $target (kit $have)." >&2
  fixit
fi
exec "$root/$target" "$@"
